GNU nano 4.4                                                                                          
packet-distrubutor.toml                                                                                                    
[general]
# Log level
#
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=5


[packet_multiplexer]
# Bind
#
# The interface:port on which the packet-multiplexer will bind for receiving
# data from the packet-forwarder (UDP data).
bind="0.0.0.0:1700"


# Backends
#
# The backends to which the packet-multiplexer will forward the
# packet-forwarder UDP data.
#
# Example:
[[packet_multiplexer.backend]]
# # Host
# #
# # The host:IP of the backend.
host="192.168.0.104:8001"
#
# # Uplink only
#
# # This backend is for uplink only. It is not able to send data
# # back to the gateways.
uplink_only=false
#
# # Gateway IDs
# #
# # The Gateway IDs to forward data for.
 gateway_ids = [
   "785EE8FFFE200DE9",
 ]


[[packet_multiplexer.backend]]
# # Host
# #
# # The host:IP of the backend.
host="10.10.82.5:8001"
#
# # Uplink only
#
# # This backend is for uplink only. It is not able to send data
# # back to the gateways.
uplink_only=false
#
# # Gateway IDs
# #
# # The Gateway IDs to forward data for.
# gateway_ids = [
#   "0101010101010101",
#   "0202020202020202",
# ]
gateway_ids = [
   "785EE8FFFE200DE9",
]


